#!/bin/sh

set -xe

curl -sL -o /usr/local/bin/shush "https://github.com/realestate-com-au/shush/releases/download/v1.5.5/shush_linux_${TARGETARCH}"

(echo "d0e091405a18b6d11a65ea1d7449802c0cbac51971031897089d038e6f7cc750  /usr/local/bin/shush" | sha256sum -c) || (echo "138af0f1eec3af50176d542fead8824c3ca0f6ba27a4a50e1db8af5959a13116  /usr/local/bin/shush" | sha256sum -c)

chmod +x /usr/local/bin/shush

shush -v

RESULT=$?

exit $RESULT
