ignored:
    - DL3018 # Pin versions in apk add - See: https://github.com/hadolint/hadolint/wiki/DL3018
    - SC2086 # For now I had troubles to do a proper quoting for PHPIZE_DEPS - See: https://github.com/koalaman/shellcheck/wiki/SC2086
