FROM php:7.2-cli-alpine3.7 as cli

# Add usabilla user and group
RUN set -x \
    && addgroup -g 1000 app \
    && adduser -u 1000 -D -G app app

# Install PHP extensions
RUN set -x \
    && apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS \
    && docker-php-ext-install pcntl \
    && docker-php-ext-install opcache \
    && pecl install apcu \
    && pecl clear-cache \
    && docker-php-ext-enable apcu \
    # Removing all PHP leftovers since the helper scripts nor the official image are removing them
    && rm -rf /usr/src/php* && rm /usr/local/bin/php-cgi && rm /usr/local/bin/phpdbg && rm -rf /tmp/pear ~/.pearrc \
    && apk del .phpize-deps

COPY common/php/conf/default.ini /usr/local/etc/php/conf.d/
COPY cli/php-cli/conf/*.ini /usr/local/etc/php/conf.d/

# Install shush
RUN set -xe \
    && curl -sL -o /usr/local/bin/shush https://github.com/realestate-com-au/shush/releases/download/v1.3.4/shush_linux_amd64 \
    && chmod +x /usr/local/bin/shush

# Install composer
COPY composer/install-composer /usr/local/bin/
RUN set -xe && install-composer

STOPSIGNAL SIGTERM

ENTRYPOINT ["/usr/local/bin/shush", "exec", "docker-php-entrypoint"]

## CLI-DEV STAGE ##
FROM cli as cli-dev

# Enable XDebug
RUN set -x \
    && apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS \
    && pecl install xdebug \
    && pecl clear-cache \
    && docker-php-ext-enable xdebug \
    && rm -rf /usr/src/php* \
    && apk del .phpize-deps 

COPY common/php/conf/debug.ini /usr/local/etc/php/conf.d/zzz_debug.ini

# Change entrypoint back to the default because we don't need shush in development
ENTRYPOINT ["docker-php-entrypoint"]
