FROM nginx:1.15-alpine as http

# <necessary users>
RUN set -x \
    && addgroup -g 1000 app \
    && adduser -u 1000 -D -G app app
# </necessary users>

# <env definition>
ENV NGINX_DOCUMENT_ROOT="/var/www/html"
ENV NGINX_SERVER_NAME=localhost
ENV NGINX_WORKERS_PROCESSES=1
ENV NGINX_WORKERS_CONNECTIONS=1024
ENV NGINX_KEEPALIVE_TIMEOUT=65
ENV NGINX_EXPOSE_VERSION=off
# </env definition>

COPY src/http/nginx/docker-nginx-location.d-enable /usr/local/bin/
COPY src/http/nginx/docker-nginx-entrypoint /usr/local/bin/

# <Nginx configuration>
COPY src/http/nginx/conf/nginx.conf.template /root/
COPY src/http/nginx/conf/vhost.conf.template /root/

## Nginx location.d add-on
COPY src/http/nginx/conf/location.d /etc/nginx/location.d-available
RUN mkdir /etc/nginx/location.d-enabled
# </Nginx configuration>

CMD ["docker-nginx-entrypoint"]

FROM http as http-dev

ENV NGINX_EXPOSE_VERSION=on
