FROM usabillabv/php-base:http

ENV NGINX_EXPOSE_VERSION=on

EXPOSE 9000

RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS \
    && pecl install xdebug-alpha \
    && docker-php-ext-enable xdebug \
    && apk del .phpize-deps

COPY common/php/conf/debug.ini /usr/local/etc/php/conf.d/zzz_debug.ini
