FROM usabillabv/php-base:cli

# Avoid xdebug installation if we don't have xdebug 2.6.0 (check can be removed after xdebug release)
RUN export XDEBUG_AVAILABLE=`pecl remote-info xdebug | grep 2.6.0 | wc -l | xargs` \
    && if [ "$XDEBUG_AVAILABLE" == "1" ]; then \
    apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del .phpize-deps \
    ;fi

COPY common/php/conf/debug.ini /usr/local/etc/php/conf.d/zzz_debug.ini
