FROM nginx:1.15-alpine as http

# <env definition>
ENV NGINX_DOCUMENT_ROOT="/var/www/html"
ENV NGINX_SERVER_NAME=localhost
ENV NGINX_WORKERS_PROCESSES=1
ENV NGINX_WORKERS_CONNECTIONS=1024
ENV NGINX_KEEPALIVE_TIMEOUT=65
ENV NGINX_EXPOSE_VERSION=off
# </env definition>

COPY http/nginx/docker-nginx-location.d-enable /usr/local/bin/

# <Nginx configuration>
COPY http/nginx/conf/nginx.conf.template /root/
COPY http/nginx/conf/vhost.conf.template /root/

## Nginx location.d add-on
COPY http/nginx/conf/location.d /etc/nginx/location.d-available
RUN mkdir /etc/nginx/location.d-enabled
# </Nginx configuration>

## From the environment variables replace the nginx configuration placeholders
CMD ESCAPE='$' envsubst < /root/vhost.conf.template > /etc/nginx/conf.d/default.conf && ESCAPE='$' envsubst < /root/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'

FROM http as http-dev

ENV NGINX_EXPOSE_VERSION=on
