version: 2

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test
  build-and-push:
    jobs:
      - http:
          context: dockerhub
          filters:
            branches:
              only: /master/
      - cli:
          context: dockerhub
          filters:
            branches:
              only: /master/
      - fpm:
          context: dockerhub
          filters:
            branches:
              only: /master/

jobs:
  http:
    machine: true
    steps:
      - checkout
      - run: make ci-push-http
  cli:
    machine: true
    steps:
      - checkout
      - run: make ci-push-cli
  fpm:
    machine: true
    steps:
      - checkout
      - run: make ci-push-fpm
  lint:
    machine: true
    steps:
      - checkout
      - run: make lint
  test:
    machine: true
    steps:
      - checkout
      - run: make build
      - run: make test
