#!/bin/sh
set -e

## From the environment variables replace the nginx configuration placeholders
ESCAPE='$' envsubst < /etc/nginx/vhost.conf.template > /etc/nginx/conf.d/default.conf \
    && ESCAPE='$' envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf \
    && nginx -g 'daemon off;'
